openapi: 3.0.0
x-stoplight:
  id: 0f56e32f16f60
info:
  title: API Università
  x-summary: Certificato Diploma di istruzione terziaria.
  version: 1.0.0
  description: |
    ### Documentazione

    ## API Università
    La seguente documentazione API fornisce un riferimento per l'integrazione e l'accesso ai dati relativi alle università italiane. 
    Queste API consentono l'erogazione di servizi (e-service) che operano sui dati universitari, offrendo informazioni riguardanti le facoltà, i corsi di studio, i programmi accademici e altre informazioni correlate. 
    Questo sistema di integrazione permette di accedere ai dati in modo efficiente e aggiornato, facilitando lo sviluppo di applicazioni e servizi che riguardano il contesto universitario.

    # Certificato Diploma di istruzione terziaria
    Questa API permette di reperire informazioni dettagliate sulla prova del diploma di istruzione terziaria, 
    certificato o laurea supplement di uno studente/ex studente tramite il suo codice fiscale o identificativo ANPR.

    **Endpoint:**   GET  /certificati/istruzione-terziaria/{taxCode}

    **Params:**    `{taxCode}`: Il Codice Fiscale (CF) dello studente o ex studente.

    **Esempio di risposta:**

    ```json
    {
      "givenName": "Mario",
      "familyName": "Rossi",
      "nameOfTertiaryEducationInstitution": "Università degli Studi di Milano",
      "nameOfStudyProgramme": "Ingegneria Informatica",
      "listOfCourseAttended": [
        {
          "nameOfCourse": "Analisi Matematica",
          "dateOfAttendance": "2022-09-01/2023-01-10",
          "gradeAchieved": "28/30"
        },
        {
          "nameOfCourse": "Fisica",
          "dateOfAttendance": "2022-09-01/2023-01-10",
          "gradeAchieved": "27/30"
        }
      ]
    }

    # Verifica stato delle API (Health Check)
    Questa API fornisce un modo semplice per verificare lo stato di salute del sistema. 
    È un endpoint di base che può essere utilizzato per controllare se il servizio è in esecuzione correttamente.

    **Endpoint:**   GET  /status
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  '/certificati/istruzione-terziaria/{taxCode}':
    get:
      summary: Certificato Diploma di istruzione terziaria
      parameters:
        - schema:
            type: string
          in: header
          name: Accept-Encoding
          description: 'Utilizzato per indicare al server le opzioni di compressione supportate dal client, come gzip o deflate.'
        - schema:
            type: string
          in: header
          name: Accept-Language
          description: 'Utilizzato per indicare al server la lingua preferita per la risposta, in modo che possa restituire la risposta nella lingua corretta, se disponibile.'
        - schema:
            type: string
          in: header
          name: Origin
          description: 'Utilizzato in contesti di sicurezza per indicare l''origine della richiesta, ad esempio durante le richieste CORS (Cross-Origin Resource Sharing).'
        - schema:
            type: string
          in: header
          name: User-Agent
          description: 'Utilizzato per identificare il client che sta effettuando la richiesta, ad esempio il browser e la versione utilizzata.'
      responses:
        '200':
          description: Richiesta eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificatoIstrTerz'
              examples:
                Example 1:
                  value:
                    givenName: Mario
                    familyName: Rossi
                    nameOfTertiaryEducationInstitution: Università degli Studi di Milano
                    nameOfStudyProgramme: Ingegneria Informatica
                    listOfCourseAttended:
                      - nameOfCourse: Analisi Matematica
                        dateOfAttendance: 2022-09-01/2023-01-10
                        gradeAchieved: 28/30
                      - nameOfCourse: Fisica
                        dateOfAttendance: 2022-09-01/2023-01-10
                        gradeAchieved: 27/30
          headers:
            Content-Length:
              schema:
                type: integer
                format: int64
              description: 'utilizzato per indicare la dimensione del corpo della risposta, consentendo al client di gestire correttamente la ricezione dei dati.'
            Cache-Control:
              schema:
                type: string
              description: 'utilizzato per indicare al client o ai server intermedi come gestire la memorizzazione nella cache della risposta, ad esempio "no-cache" per impedire la memorizzazione nella cache.'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: utilizzato per consentire a determinati origini di accedere alle risorse tramite richieste cross-origin.
            X-RateLimit-Limit:
              schema:
                type: integer
                format: int32
              description: specifica il numero massimo di richieste consentite entro un determinato periodo di tempo (solitamente misurato in secondi).
            X-RateLimit-Remaining:
              schema:
                type: integer
                format: int32
              description: utilizzato per indicare il numero di richieste API rimanenti all'interno del periodo di tempo specificato dal server.
            X-RateLimit-Reset:
              schema:
                type: string
                format: date-time
              description: utilizzato per indicare il momento in cui il limite delle richieste API verrà ripristinato.
        '404':
          description: Diploma di istruzione terziaria non trovato
          headers:
            Content-Length:
              schema:
                type: integer
                format: int64
              description: 'utilizzato per indicare la dimensione del corpo della risposta, consentendo al client di gestire correttamente la ricezione dei dati.'
            Cache-Control:
              schema:
                type: string
              description: 'utilizzato per indicare al client o ai server intermedi come gestire la memorizzazione nella cache della risposta, ad esempio "no-cache" per impedire la memorizzazione nella cache.'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: utilizzato per consentire a determinati origini di accedere alle risorse tramite richieste cross-origin.
            X-RateLimit-Limit:
              schema:
                type: integer
                format: int32
              description: specifica il numero massimo di richieste consentite entro un determinato periodo di tempo (solitamente misurato in secondi).
            X-RateLimit-Remaining:
              schema:
                type: integer
                format: int32
              description: utilizzato per indicare il numero di richieste API rimanenti all'interno del periodo di tempo specificato dal server.
            X-RateLimit-Reset:
              schema:
                format: int32
                maximum: 186400
                minimum: 0
                type: integer
              description: utilizzato per indicare il momento in cui il limite delle richieste API verrà ripristinato.
        '500':
          description: Errore interno del server
          headers:
            Content-Length:
              schema:
                type: integer
                format: int64
              description: 'utilizzato per indicare la dimensione del corpo della risposta, consentendo al client di gestire correttamente la ricezione dei dati.'
            Cache-Control:
              schema:
                type: string
              description: 'utilizzato per indicare al client o ai server intermedi come gestire la memorizzazione nella cache della risposta, ad esempio "no-cache" per impedire la memorizzazione nella cache.'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: utilizzato per consentire a determinati origini di accedere alle risorse tramite richieste cross-origin.
            X-RateLimit-Limit:
              schema:
                type: integer
                format: int64
              description: specifica il numero massimo di richieste consentite entro un determinato periodo di tempo (solitamente misurato in secondi).
            X-RateLimit-Remaining:
              schema:
                type: integer
                format: int64
              description: utilizzato per indicare il numero di richieste API rimanenti all'interno del periodo di tempo specificato dal server.
            X-RateLimit-Reset:
              schema:
                type: string
                format: date-time
              description: utilizzato per indicare il momento in cui il limite delle richieste API verrà ripristinato.
      description: Restituisce i dati per il certificato di istruzione terziaria
      operationId: certificato-istruzione-terziaria
      tags:
        - CERTIFICATO-ISTRUZIONE-TERZIARIA
    parameters:
      - schema:
          type: string
        name: taxCode
        in: path
        description: Codice fiscale dello studente o identificativo ANPR
        required: true
  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      operationId: check-status
      description: Verificare lo stato di salute del sistema
      tags:
        - HEALTH-CHECK
      responses:
        '204':
          description: il servizio è in esecuzione correttamente.
        '500':
          description: il servizio non è in esecuzione.
components:
  schemas:
    CertificatoIstrTerz:
      type: object
      x-examples:
        Example 1:
          givenName: Mario
          familyName: Rossi
          nameOfTertiaryEducationInstitution: Università degli Studi di Milano
          nameOfStudyProgramme: Ingegneria Informatica
          listOfCourseAttended:
            - nameOfCourse: Analisi Matematica
              dateOfAttendance: 2022-09-01/2023-01-10
              gradeAchieved: 28/30
            - nameOfCourse: Fisica
              dateOfAttendance: 2022-09-01/2023-01-10
              gradeAchieved: 27/30
      properties:
        givenName:
          type: string
          example: Mario
          description: Nome dello studente
          readOnly: true
        familyName:
          type: string
          example: Rossi
          description: Cognome dello studente
          readOnly: true
        nameOfTertiaryEducationInstitution:
          type: string
          description: Nome istituto di istruzione terziaria
          readOnly: true
        nameOfStudyProgramme:
          type: string
          description: Nome del corso di studio
          readOnly: true
        listOfCourseAttended:
          type: array
          description: Elenco dei corsi frequentati
          items:
            type: object
            properties:
              nameOfCourse:
                type: string
                description: Nome del corso
                readOnly: true
              dateOfAttendance:
                type: string
                description: Time interval of the date of attendance in ISO8601 format.
                example: 2021-10-01/2022-02-15
                description: Data di partecipazione al corso
                pattern: '^\d{4}-\d{2}-\d{2}/\d{4}-\d{2}-\d{2}$'
                readOnly: true
              gradeAchieved:
                type: string
                pattern: ^(\d+L?)/\d+$
                description: |-
                  Voto ottenuto al corso (rapporto tra voto/votoMax).

                  Mettere tra gli esempi la serializzazione della lode (e.g., 110L/100).
                readOnly: true
      description: Certificazione diploma istruzione terziaria
  requestBodies: {}
  responses: {}
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: API-UNIVERSITÀ
  - name: CERTIFICATO-ISTRUZIONE-TERZIARIA
  - name: HEALTH-CHECK

